<?php

define('TWITTER_CONSUMER_KEY', env('TWITTER_CONSUMER_KEY'));
define('TWITTER_CONSUMER_SECRET', env('TWITTER_CONSUMER_SECRET'));
define('OAUTH_TOKEN', env('OAUTH_TOKEN'));
define('OAUTH_SECRET', env('OAUTH_SECRET'));
